language: r
r:
  - oldrel
  - release
  - devel
cache: packages

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling

r_binary_packages:
 - knitr
 - rmarkdown

before_install:
 - cd ~$USER
 - wget http://www.hdfql.com/releases/2.0.1/HDFql-2.0.1_Linux64_GCC-4.9.zip
 - echo $PWD
 - unzip HDFql-2.0.1_Linux64_GCC-4.9.zip
 - export HDFQL_DIR=~$USER/HDFql-2.0.1
 - echo $HDFQL_DIR
 - cd ~$USER/hdfqlr 
 - cp -f inst/HDFql.R $HDFQL_DIR/wrapper/R/HDFql.R 
