language: r
r:
  - oldrel
  - release
  - devel
sudo: required
cache: packages

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling

r_binary_packages:
 - knitr
 - rmarkdown

before_install:
 - wget http://www.hdfql.com/releases/2.0.1/HDFql-2.0.1_Linux64_GCC-4.9.zip
 - unzip HDFql-2.0.1_Linux64_GCC-4.9.zip -d HDFQLINSTALLDIR
 - export HDFQL_DIR=$PWD/HDFQLINSTALLDIR/HDFql-2.0.1

before_script:
 - cp -f hdfqlr/inst/HDFql.R $HDFQL_DIR/wrapper/R/HDFql.R 
