dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

language: r
r:
  - oldrel
  - release
  - devel
cache: packages

r_packages:
  - covr

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HDFql

env:
  matrix:
    - HDFQL_VERSION="2.1.0"


before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - cd ..
  - echo $PWD
  - wget http://www.hdfql.com/releases/${HDFQL_VERSION}/HDFql-${HDFQL_VERSION}_Linux64_GCC-4.9.zip
  - unzip HDFql-${HDFQL_VERSION}_Linux64_GCC-4.9.zip
  - export HDFQL_DIR=${PWD}/hdfql-${HDFQL_VERSION}
  - echo $HDFQL_DIR
  - cd -
  - if [ ! -d "$HDFQL_DIR" ]; then echo  "HDFql directory does not exist."; fi
  - export LD_LIBRARY_PATH = ${HDFQL_DIR}/lib:${HDFQL_DIR}/wrapper/R:${LD_LIBRARY_PATH}

after_success:
  - Rscript -e 'library(covr); codecov()'