language: r
r:
  - oldrel
  - release
  - devel
cache: packages


# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling

r_binary_packages:
 - knitr
 - rmarkdown

env:
  global:
    - CAMPFIRE_TOKEN=abc123
    - TIMEOUT=1000
  matrix:
    - HDFQL_VERSION=2.1.0

before_install:
 - cd ~
 - wget http://www.hdfql.com/releases/2.1.0/HDFql-$HDFQL_VERSION_Linux64_GCC-4.9.zip
 - echo $PWD
 - unzip HDFql-$HDFQL_VERSION_Linux64_GCC-4.9.zip
 - export HDFQL_DIR=~/hdfql-$HDFQL_VERSION
 - echo $HDFQL_DIR
 - cd ~- 
