language: r
r:
  - oldrel
  - release
  - devel
cache: packages

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling

r_binary_packages:
 - knitr
 - rmarkdown

before_install:
 - cd ~
 - wget http://www.hdfql.com/releases/2.1.0/HDFql-2.1.0_Linux64_GCC-4.9.zip
 - echo $PWD
 - unzip HDFql-2.1.0_Linux64_GCC-4.9.zip
 - export HDFQL_DIR=~/hdfql-2.1.0
 - echo $HDFQL_DIR
 - cd ~- 
